apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cdd-integration-data-store-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.data_store_storage }}
