apiVersion: v1
kind: Service
metadata:
  name: cdd-integration
  labels:
    app.kubernetes.io/name: cdd-integration
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cdd-integration
  ports:
    - port: 9100
      targetPort: 9100
      protocol: TCP